spring:
  application:
    name: mm-workboard-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://mm-config-server:1881"

eureka:
  client:
    service-url:
      defaultZone: http://mm-eureka-server:1761/eureka/

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml