spring:
  application:
    name: mm-workboard-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://mm-config-server:1882"

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml