server:
  port: 1993

spring:
  application:
    name: mm-workboard-service

  config:
    import: "optional:configserver:http://localhost:1881"

  datasource:
    url: jdbc:mysql://localhost:3306/liveshop
    username: liveshop
    password: "1234"

mybatis:
  type-aliases-package: co.kr.mmsoft.mmworkboardservice
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    # db컬럼명 account_id ==> java 객체 accountId
    map-underscore-to-camel-case: true

my:
  logging:
    level: debug

logging:
  level:
    root: info

    #spring security 관련
    org.flywaydb: ${my.logging.level}
    org.springframework.security:  ${my.logging.level}
    org.springframework.security.web:  ${my.logging.level}
    org.springframework.security.authentication:  ${my.logging.level}
    org.springframework.security.authorization:  ${my.logging.level}

    # spring web ㄱ환련
    org.springframework.web: ${my.logging.level}
    org.springframework.web.servlet.DispatcherServlet: ${my.logging.level}

    co.kr.mmsoft.mmworkboardservice: ${my.logging.level}

# mm-member-service의 설정 파일
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1761/eureka/